version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
  
  backend:
    build:
      context: ../../Downloads
      dockerfile: Dockerfile
    ports:
      - "9000:9000"